name: wit_app
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: mert <utarit.543@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  # This is necessarry for http requests
 http:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
